services:
  ase-bot:
    image: ghcr.io/seyfu-t/ase-discord-bot:latest
    container_name: ase-discord-bot
    # Comment out as needed
    # env_file:
    #   - .env
    # environment:
    #   - TMDB_READ_ACCESS_TOKEN=
    #   - DISCORD_TOKEN=
    #   - DISCORD_GUILD_ID=
    #   - DISCORD_AVATAR=
    #   - DISCORD_BANNER=
    #   - DISCORD_USERNAME=
    #   - OPEN_ROUTER_API_KEY=
    restart: unless-stopped
