name: Linting & Formatting

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8 pre-commit

      - name: Run pre-commit hooks (flake8, autopep8)
        run: pre-commit run --all-files --show-diff-on-failure
